"""
VSM Backend – Models Package

With Prisma ORM, the database models are auto-generated by `prisma generate`.
This package re-exports Python enums for use across the application.

Prisma-generated model classes are available via:
    from prisma.models import Task, EventLog, TaskStatus, ...

Python enums (for type hints and validation) are here:
    from app.models.enums import TaskStatusCategory, EventType, ...
"""

from app.models.enums import (  # noqa: F401
    TaskStatusCategory,
    EventType,
    EventSource,
    QueueStatus,
    WindowStatus,
    ActivityType,
    DetectedIntent,
    FeedbackResult,
    CorrectedIntent,
    MappingMethod,
    DecisionSource,
)

__all__ = [
    "TaskStatusCategory",
    "EventType",
    "EventSource",
    "QueueStatus",
    "WindowStatus",
    "ActivityType",
    "DetectedIntent",
    "FeedbackResult",
    "CorrectedIntent",
    "MappingMethod",
    "DecisionSource",
]
